### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by vicmosin** [zalari/docker-nginx-html5#1]
After running the following commands and copying dist `COPY dist /usr/share/nginx/html`:

```
npm install
ng build
```

I get the following error while running the container:

```
dev_web.1.3b6022h48r94@dev    | > Parsing json
dev_web.1.3b6022h48r94@dev    | cp: cannot stat '/usr/share/nginx/html/config.json': No such file or directory
dev_web.1.3b6022h48r94@dev    | jq: error: Could not open file /usr/share/nginx/html/config.json: No such file or directory
```

**Comment by ChristianUlbrich** [comment]
This was a regression because we added some internal logic and kind of forgot to document this. The latestest version 2.0 fixes this, by reverting to the old behavior.
